#!/bin/bash
#
NOCOLOR='\033[0m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;32m'
MAGENTA='\033[0;35m'
RED='\033[0;31m'

protected_branch='main'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]; then
  echo -e "${RED}ATTENTION:$NOCOLOR You are on protected ${RED}branch $protected_branch${NOCOLOR}"
  read -p "Are you sure you want to push here? (yes/no) " -n 3 -r < /dev/tty
  echo
  if echo $REPLY | grep -E '^[Yy][Ee][Ss]$' > /dev/null; then
    exit 0 # push will execute
  fi
  exit 1 # push will not execute
else
  exit 0 # push will execute
fi
