volumes:
  tesla_ble_mqtt:
    external: true

services:
  tesla_ble_mqtt:
    container_name: tesla_ble_mqtt
    image: "iainbullock/tesla_ble_mqtt:latest"

    # Configuration Settings have been moved to the "stack.env" file
    env_file:
      - stack.env

    # Needed to open the Bluetooth dongle to send commands to the car
    network_mode: host
    privileged: true

    # TODO: Needed to open the Bluetooth device. 
    # Reply: I think it is needed to get a container shell which is a useful diagnostic
    tty: true

    # TODO : Why?
    # Reply: I think it is needed to get a container shell which is a useful diagnostic
    stdin_open: true

    # TODO : still valid?
    # Reply: It seems to work after I remmed it out
    # working_dir: /share/tesla_ble_mqtt

    volumes:
      - tesla_ble_mqtt:/share/tesla_ble_mqtt
      - /run/dbus:/run/dbus

    # Uncomment if you need a container shell when the container won't run 
    # entrypoint: "/bin/ash"

    # Uncommenting restart: unless-stopped is recommended when the container is fully configured and working correctly    
    restart: no
    #restart: unless-stopped
