volumes:
  tesla_ble_mqtt:
    external: true

services:
  tesla_ble_mqtt:
    container_name: tesla_ble_mqtt
    image: "iainbullock/tesla_ble_mqtt:latest"
    #image: "tesla_ble_mqtt:latest"

    # Configuration Settings have been moved to the "stack.env" file
    env_file:
      - stack.env

    # Needed to open the Bluetooth dongle to send commands to the car
    network_mode: host
    privileged: true

    # Allow opening of a shell in container
    tty: true
    stdin_open: true

    volumes:
      - tesla_ble_mqtt:/share/tesla_ble_mqtt
      - /run/dbus:/run/dbus

    # Uncomment if you need a container shell when the container won't run 
    # entrypoint: "/bin/ash"

    restart: unless-stopped
